### PR TITLE
Adding support for Summit and Theta

### PR DESCRIPTION
**Pull request by lxAltria**
NOTE: The script cannot make all the submissions on Theta because default queue requires scale >= 128 nodes while debug queue only allows one submission.

### CODE REVIEW

**Comment by pnorbert** [comment]
Can you please fix the writer and reader exe to be plain adios2_iotest instead of a fixed path in your home?
We need to run these with adios2, tau and codar-cheetah spack packages loaded. 

@kshitij-v-mehta: do we always need to copy the binaries to the input directory or use full path, or can you find executables in the path? How can we set up the campaign definition so that we can create the campaigns without looking extra editing/file copying?

**Comment by lxAltria** [comment]
Sure. It is fixed now. Is there any other issue that needs to be addressed?

**Comment by pnorbert** [comment]
I am missing the SSC and BP4+BurstBuffer tests on Summit and Theta. I understand that some of them is not possible right now, like MPMD mode on Rhea, SSC currently does not work on Summit and the BurstBuffer use requires a job script explicitly asking for it on those machine.

**Comment by kshitij-v-mehta** [comment]
> do we always need to copy the binaries to the input directory or use full path, or can you find executables in the path?

Cheetah does not look at PATH for the binaries. They have to be in the input dir or the spec file has to contain the full path.

**Comment by pnorbert** [comment]
Thanks for the answer. However, both options will require messing with the files/directory after checking out the repository. It is certainly possible to find the adios2_iotest with spack and copy it but it would be nice if cheetah just could rely on loading a module/spack package/setting path in the setup_env script and launching an executable. TAU does that, this works fine:
```
$ spack load adios2
$ spack load tau
$ tau_exec adios2_iotest ...
```

**Comment by kshitij-v-mehta** [comment]
Ok, then let me make that change in Cheetah so that it does not require the app executable paths to be specified.

**Pull request merged**
